services:
  weblatex:
    build: .
    image: weblatex
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/weblatex:/app/weblatex/compiler_workspace